M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Sun 06 Mar 2022 07:09:21 PM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-06T19:09:21-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X61.8Y-220.0
X196.2Y-177.2
X330.6Y-220.0
T0
M30
